spring.application.name=cruddemo

#connect to database
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent



springdoc.swager-ul.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs




# Turn off Baner
spring.main.banner-mode=off

#reduce logging lvl
#logging.level.root=warn


# Add logging confid to display sql statement
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace



management.endpoints.web.exposure.include=*





